### ISSUE TITLE
JWT token issue 

### ISSUE THREAD

**Issue by mominrazashahid** [codergogoi/nodejs_microservice#1]
Hi, when I log in as a **customer** on the local host using this URL `{{CUSTOMER_BASE}}/login` token generate successfully. 
When I hit the other API and add the **Authorization** token I got the error  `jwt expired`also service get down I also add a try-catch also update the **jsonwebtoken** package.
`return done(new TokenExpiredError('jwt expired', new Date(payload.exp * 1000)));
                    ^
TokenExpiredError: jwt expired`

### Here is how the token is generated. 
`return await jwt.sign(payload, APP_SECRET, { expiresIn: "1d" });`

### how the token is verifying.
`try {
        console.log(APP_SECRET,'APP_SECRET')
        const payload = jwt.verify(signature.split(" ")[1], APP_SECRET);
        req.user = payload;
        return true;
      } catch(err) {
        console.log(err,'err');
        return false;
      }`

**Comment by codergogoi** [comment]
resolved on master!

**Comment by mominrazashahid** [comment]
thanks issue resolved
